### ISSUE TITLE
Does not build with Clang 3.3

### ISSUE THREAD

**Issue by bubbles231** [flygoast/opentracker#2]
I am trying to rebuild the libowfat-0.29 from a Debian unstable source package with
Clang.

../CAS.h:56:3: error: void function 'atomic_add' should not return a value [-Wreturn-type]
  return __sync_add_and_fetch(x,val);
  ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by bubbles231** [comment]
By the way if you just remove the return like this:
__sync_add_and_fetch(x,val);

It builds fine.

**Comment by flygoast** [comment]
looks good to me.
